const PDFDocument = require('pdfkit');

/**
 * Generate official Academic Report Card PDF and stream to HTTP response
 */
const generateReportCardPDF = (student, grades, attendanceStats, res) => {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="ReportCard_${student.rollNumber || 'Student'}.pdf"`
  );

  doc.pipe(res);

  // Header Banner
  doc.rect(40, 40, 515, 75).fill('#1e293b'); // Slate-900

  doc.fillColor('#ffffff').fontSize(18).text('CAMPUSLEDGER UNIVERSITY', 50, 55, { align: 'center' });
  doc.fontSize(10).text('OFFICIAL SEMESTER ACADEMIC TRANSCRIPT & REPORT CARD', 50, 80, { align: 'center' });
  doc.fontSize(8).fillColor('#94a3b8').text('Accredited Grade A+ Institution • Academic Year 2025-2026', 50, 96, { align: 'center' });

  // Student Info Card
  doc.rect(40, 125, 515, 80).fill('#f8fafc').stroke('#cbd5e1');

  doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold');
  doc.text('Student Name:', 55, 140);
  doc.text('Roll Number:', 55, 158);
  doc.text('Department:', 55, 176);

  doc.font('Helvetica');
  doc.text(student.name || 'N/A', 135, 140);
  doc.text(student.rollNumber || 'N/A', 135, 158);
  doc.text(student.department || 'N/A', 135, 176);

  doc.font('Helvetica-Bold');
  doc.text('Semester / Sec:', 320, 140);
  doc.text('Attendance Rate:', 320, 158);
  doc.text('Date of Issue:', 320, 176);

  doc.font('Helvetica');
  doc.text(`Semester ${student.semester || 1} - Sec ${student.section || 'A'}`, 415, 140);

  const attPct = attendanceStats?.percentage ? `${attendanceStats.percentage}%` : 'N/A';
  if (attendanceStats?.lowAttendanceWarning) {
    doc.fillColor('#dc2626').font('Helvetica-Bold').text(`${attPct} (Warning: <75%)`, 415, 158);
  } else {
    doc.fillColor('#16a34a').text(attPct, 415, 158);
  }

  doc.fillColor('#0f172a').font('Helvetica').text(new Date().toLocaleDateString(), 415, 176);

  // Grades Table Header
  let startY = 225;
  doc.rect(40, startY, 515, 24).fill('#334155');
  doc.fillColor('#ffffff').fontSize(9).font('Helvetica-Bold');
  doc.text('#', 50, startY + 7);
  doc.text('Subject Name', 75, startY + 7);
  doc.text('Exam Type', 260, startY + 7);
  doc.text('Credits', 345, startY + 7);
  doc.text('Marks', 400, startY + 7);
  doc.text('Grade', 455, startY + 7);
  doc.text('Points', 505, startY + 7);

  // Grades Table Rows
  startY += 24;
  let totalCredits = 0;
  let totalWeightedPoints = 0;

  if (grades && grades.length > 0) {
    grades.forEach((g, index) => {
      const isEven = index % 2 === 0;
      doc.rect(40, startY, 515, 20).fill(isEven ? '#ffffff' : '#f1f5f9').stroke('#e2e8f0');

      const credits = Number(g.credits) || 3;
      const gp = Number(g.gradePoint) || 0;
      totalCredits += credits;
      totalWeightedPoints += gp * credits;

      doc.fillColor('#1e293b').fontSize(8).font('Helvetica');
      doc.text(String(index + 1), 50, startY + 6);
      doc.text(g.subject || 'Subject', 75, startY + 6, { width: 175, ellipsis: true });
      doc.text(g.examType || 'Final', 260, startY + 6);
      doc.text(String(credits), 350, startY + 6);
      doc.text(`${g.marksObtained}/${g.maxMarks || 100}`, 400, startY + 6);
      doc.text(g.gradeLetter || 'A', 460, startY + 6);
      doc.text(String(gp), 510, startY + 6);

      startY += 20;
    });
  } else {
    doc.rect(40, startY, 515, 25).fill('#ffffff').stroke('#e2e8f0');
    doc.fillColor('#64748b').fontSize(9).text('No recorded grades found for the selected semester.', 50, startY + 8, { align: 'center' });
    startY += 25;
  }

  // Summary Metrics Footer
  const computedGPA = totalCredits > 0 ? (totalWeightedPoints / totalCredits).toFixed(2) : '0.00';
  startY += 15;

  doc.rect(40, startY, 515, 45).fill('#f8fafc').stroke('#cbd5e1');
  doc.fillColor('#0f172a').fontSize(10).font('Helvetica-Bold');
  doc.text(`Total Credits Earned: ${totalCredits}`, 60, startY + 16);
  doc.text(`Semester GPA: ${computedGPA}`, 220, startY + 16);
  doc.fillColor('#2563eb').text(`Cumulative CGPA: ${attendanceStats?.cgpa || computedGPA}`, 380, startY + 16);

  // Signatures Area
  startY += 80;
  doc.strokeColor('#94a3b8').lineWidth(1);
  doc.moveTo(60, startY).lineTo(180, startY).stroke();
  doc.moveTo(230, startY).lineTo(350, startY).stroke();
  doc.moveTo(400, startY).lineTo(520, startY).stroke();

  doc.fillColor('#475569').fontSize(8).font('Helvetica');
  doc.text('Prepared By (Faculty)', 60, startY + 8, { width: 120, align: 'center' });
  doc.text('Head of Department', 230, startY + 8, { width: 120, align: 'center' });
  doc.text('Controller of Examinations', 400, startY + 8, { width: 120, align: 'center' });

  // Security Watermark / Footer
  doc.fontSize(7).fillColor('#94a3b8').text(
    `This report card is digitally generated by CampusLedger SMS on ${new Date().toISOString()} • Verification Token: CL-${student._id?.toString().slice(-8).toUpperCase()}`,
    40,
    760,
    { align: 'center', width: 515 }
  );

  doc.end();
};

/**
 * Generate Student ID Card PDF and stream to HTTP response
 */
const generateIdCardPDF = (student, res) => {
  // CR80 ID Card dimensions roughly 242 x 153 pt
  const doc = new PDFDocument({ size: [320, 200], margin: 10 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader(
    'Content-Disposition',
    `attachment; filename="ID_Card_${student.rollNumber || 'Student'}.pdf"`
  );

  doc.pipe(res);

  // Outer Border & Card Background
  doc.roundedRect(10, 10, 300, 180, 8).fillAndStroke('#ffffff', '#1e293b');

  // Top Header Banner
  doc.roundedRect(10, 10, 300, 42, 8).fill('#1e293b');
  doc.rect(10, 30, 300, 22).fill('#1e293b'); // Fill lower rounded corners

  doc.fillColor('#ffffff').fontSize(11).font('Helvetica-Bold').text('CAMPUSLEDGER UNIVERSITY', 10, 17, { align: 'center', width: 300 });
  doc.fontSize(7).font('Helvetica').fillColor('#38bdf8').text('STUDENT IDENTITY CARD', 10, 32, { align: 'center', width: 300 });

  // Avatar Placeholder Box
  doc.roundedRect(20, 62, 65, 75, 4).fillAndStroke('#e2e8f0', '#94a3b8');
  doc.fillColor('#64748b').fontSize(8).font('Helvetica-Bold').text('PHOTO', 20, 95, { align: 'center', width: 65 });

  // Student Details
  doc.fillColor('#0f172a').fontSize(8).font('Helvetica-Bold');
  doc.text('Name:', 95, 64);
  doc.text('Roll No:', 95, 78);
  doc.text('Dept:', 95, 92);
  doc.text('Sem/Sec:', 95, 106);
  doc.text('Blood Grp:', 95, 120);
  doc.text('Phone:', 95, 134);

  doc.font('Helvetica').fillColor('#334155');
  doc.text(student.name || 'N/A', 145, 64, { width: 155, ellipsis: true });
  doc.font('Helvetica-Bold').fillColor('#2563eb').text(student.rollNumber || 'N/A', 145, 78);
  doc.font('Helvetica').fillColor('#334155').text(student.department || 'N/A', 145, 92, { width: 155, ellipsis: true });
  doc.text(`Semester ${student.semester || 1} / ${student.section || 'A'}`, 145, 106);
  doc.text(student.bloodGroup || 'O+', 145, 120);
  doc.text(student.phone || 'N/A', 145, 134);

  // Bottom Footer Strip
  doc.rect(10, 155, 300, 35).fill('#f1f5f9');
  doc.fillColor('#475569').fontSize(6).font('Helvetica').text('Authorized Signatory: Registrar Office • Valid for 2025-2026 Academic Year', 10, 162, { align: 'center', width: 300 });
  doc.fillColor('#0284c7').fontSize(6).font('Helvetica-Bold').text('Emergency: +1 (800) 555-0199 • portal.campusledger.edu', 10, 172, { align: 'center', width: 300 });

  doc.end();
};

module.exports = { generateReportCardPDF, generateIdCardPDF };
